# SPDX-FileCopyrightText: 2024 The JMP.boot Developers
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "nightly"
components = ["rust-src", "rust-std", "rustfmt", "clippy", "llvm-tools-preview"]
targets = ["aarch64-unknown-none", "aarch64-unknown-uefi", 
    "x86_64-unknown-uefi", "x86_64-unknown-none", 
    "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
